### ISSUE TITLE
speed:test does not work and provides no measurement

### ISSUE THREAD

**Issue by kareltrcalek** [mjphaynes/php-resque#52]
Hi folks,
 I have a problem with speed:test, the problem is that it exits after 1st second of running the speed test and it never shows any measurement values at all. If I want for example test that takes 100 seconds, it does not matter and programm exits always after 1st second.

![speed_test_php_resque](https://cloud.githubusercontent.com/assets/22789234/25383622/31170ac4-29bd-11e7-8530-6acf9f3139c4.JPG)

**Comment by xelan** [comment]
HI @kareltrcalek!

Did you try to run the speed test from within a project? If php-resque is the root package , the speed test works fine for me - see the example below. Maybe there's a problem with path/autoloader resolution for the test configuration file if php-resque is not the root package.

```bash
git clone https://github.com/mjphaynes/php-resque.git
cd php-resque
composer install
bin/resque speed:test
```  

```
Finished php-resque speed test
===================================
Time:         10s
Processed:    192 jobs
Speed:        19.2 jobs/s
Avg job time: 52.1 ms
```

**Comment by kareltrcalek** [comment]
Hi @xelan,
 yeah you are right, it works only from within this project, outside does not work. Thanks a lot! 👍

**Comment by xelan** [comment]
You're welcome :smile: Thanks for reporting this issue. I'll keep it open as a reminder to check the speed test autoloading.

**Comment by xelan** [comment]
Hi @kareltrcalek!

The issue here is the hard-coded path to the configuration file in [the speed test folder](https://github.com/mjphaynes/php-resque/blob/master/test/speed/config.yml). While this works in the default settings (local Redis, php-resque as project root), it does not work with a different setup.

One approach might be to allow a custom configuration file path instead of [RESQUE_DIR/test/speed/config.yml](https://github.com/mjphaynes/php-resque/blob/master/src/Resque/Commands/SpeedTest.php#L48).

To run the speed test with a custom configuration, probably copying the aforementioned `config.yml` and adapting the Redis and logging configuration would probably be the best option for the user.

For example, the speed test could then be done like this:
```sh
cp vendor/mjphaynes/php-resque/test/speed/config.yml ./speedtest_config.yml
vi speedtest_config.yml
```
```yaml
# speedtest_config.yml
include: vendor/mjphaynes/php-resque/test/speed/autoload.php

redis:
    scheme: tcp
    host: redis.example.net
    port: 6379
    namespace: "resque:speedtest"

default:
    expiry_time: 1
    verbose: 2
    workers:
        blocking: true
        interval: 1

log:
    stream: path/to/custom.log
```

```sh
vendor/bin/resque speed:test -c speedtest_config.yml
```

What do you think about this possible solution?
