### ISSUE TITLE
Worker can not pop last queue in PHP7.1

### ISSUE THREAD

**Issue by davidtall** [mjphaynes/php-resque#61]
This is My config.yml file:
```
default:
     expiry_time: 604800 # Default expiry time of Redis keys
     #verbose:           # quiet=0, normal=1, verbose=2, very_verbose=3, debug=4
     #jobs:
         #queue: default  # Defalt queue to add a job to
         #delay: false    # Default delay to add to jobs false=no delay
     workers:
         queue: "*"      # Default queue to watch, *=all queues
         blocking: false  # Use Redis blocking
         interval: 1    # Worker interval (seconds)
         timeout: 60     # Job timeout (seconds)
         memory: 128     # Max worker memory
         #pid: 20088     # Max worker memory
```
First ,I push 100 jobs into redis by random queue:
```
for($i=0;$i<100;$i++){
       Resque::push('Open\\Job\\TestJob', array(), "shop" . mt_rand(1, 100));
}
```
Then ,I start one worker by running command `bin/resque worker:start -vvv`
the worker finish jobs,and the main process into `Worker: waiting for job on * with interval 1 second` status.
But I see the redis ,There are still three jobs not processed,They belong to the last queue named "resque:queue:shop99".
then I debug the source code
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Queue.php#L127-L145

I insert debug code `print_r($queue.PHP_EOL)` into L140 and restart worker.
```
foreach ($queues as $queue) {
    print_r($queue.PHP_EOL);
    if ($payload = $this->redis->lpop($queue)) {
           break;
    }
}
```
It can not print queue "queue:shop99",but print queue "queue:shop98" twice.
I think the problem is because line 131 use `&`
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Queue.php#L131
So I modify `$queue` into `$q` in line 139 like that:
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Queue.php#L139
```
foreach ($queues as $q) {
        print_r($q.PHP_EOL);
        if ($payload = $this->redis->lpop($q)) {
               $queue = $q;
               break;
         }
}
```
Restart the worker ,It can print "queue:shop99" and perform last three jobs successfully.
So I'm sure that It's a bug beacause PHP7 foreach feature ,see http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.array-order

I think the better way to fix this bug is replace Line 131 with 
```
        foreach ($queues as $key=>$queue) {
            $queues[$key] = self::redisKey($queue);
        }
```
instead using `&$queue` @francislavoie @mjphaynes @xelan
