### ISSUE TITLE
A Exception When I stop worker : Unsupported operand types

### ISSUE THREAD

**Issue by davidtall** [mjphaynes/php-resque#64]
This is my cofig.yml file :
```
redis:
     scheme: tcp         # The connection scheme
     host: 10.27.168.117
     port: 6379          # The port to connect to
     password: xxx          # The port to connect to
     namespace: resque   # The key prefix in Redis
     rw_timeout: 60      # Redis read/write timeout
     phpiredis: false    # Should use phpiredis php extension (must be installed)


default:
     expiry_time: 604800 # Default expiry time of Redis keys
     #verbose:           # quiet=0, normal=1, verbose=2, very_verbose=3, debug=4
     #jobs:
         #queue: default  # Defalt queue to add a job to
         #delay: false    # Default delay to add to jobs false=no delay
     workers:
         queue: "*"      # Default queue to watch, *=all queues
         blocking: true  # Use Redis blocking
         interval: 1    # Worker interval (seconds)
         timeout: 60     # Job timeout (seconds)
         memory: 128     # Max worker memory
         #pid: 20088     # Max worker memory
```
First ,I start two woker on one machine,and add 1000 jobs into queue:
```
   for($i=0;$i<1000;$i++){
            \Resque::push('Open\\Job\\TestJob', array(), "shop" . mt_rand(1, 100));
        }
```
not until all jobs was processed,I run command `resque worker:stop` to stop woker.
One of the workers throw a exception :`Unsupported operand types` in src/Resque/Worker.php(787)
then I debug it,
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Worker.php#L765
I find that `$found` return a empty array,So I log here like that:
```
 list($jobs, $found) = $res=$this->redis->exec();
 if(is_array($found)){
                $this->log(var_export($res,true), Logger::NOTICE);
            }
```
then I retry the case many times (It does not appear every times), the log file record :
```
[2017-09-03 14:57:43] resque.INFO: Done job shop54:Open\Job\TestJob#21075b4615e468768e61fd() in 8.2ms [] []
[2017-09-03 14:57:43] resque.INFO: Done job shop54:Open\Job\TestJob#21075b4615e46876a27ce5() in 7.4ms [] []
[2017-09-03 14:57:43] resque.DEBUG: QUIT received; shutdown worker [] []
[2017-09-03 14:57:43] resque.NOTICE: array (   0 =>    Predis\Response\Status::__set_state(array(      'payload' => 'OK',   )),   1 =>    array (   ),   2 => 0, ) [] []
```
I don't know why !
https://github.com/mjphaynes/php-resque/blob/8ec37dbcde8fbf4088efd2385cc015f765ec16da/src/Resque/Worker.php#L760-L763

Why does It return three  elements after `$this->redis->exec()`?
@francislavoie @xelan
