### ISSUE TITLE
Cannot use 'KEYS' with redis-cluster.

### ISSUE THREAD

**Issue by fredams** [mjphaynes/php-resque#93]
Hi, 
i'm using predis, but when i start the workers i'm getting this message:

```
** [12:21:53 2019-10-25] Starting worker 
                                       
  [Predis\NotSupportedException]         
  Cannot use 'KEYS' with redis-cluster.  
```

Config file:
```
predis:
  namespace:  namespace
  config:
    - "tcp://server1:9991"
    - "tcp://server1:9992"
    - "tcp://server1:9993"
  options:
    cluster: "redis"
```

Can anyone help me please? 
thanks
